data:
  APPINSIGHTS_INSTRUMENTATIONKEY: MGQ3NWZiMDItZDNmNi00N2UxLWJkYjYtNzdhNTBiY2IyNmI3
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9dWRjdGF6bWNzdGc7QWNjb3VudEtleT1PekRqeUFXWE1ReGJGR01VcXpZNkdreS9RRkZzZmZtRDRxbXVQaEtkTDd1c2t2OFNQQ3RQUTRuQTJwL05OK2s3K2tNVHY1THdJcTRPK0FTdFJmcHVBUT09
  FUNCTIONS_EXTENSION_VERSION: fjM=
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  MyDbConnection: bW9uZ29kYjovL2F6bWNjb3Ntb3NkYjpmYmdhaDBDcjdHZU1GVGMxMFp1SWxQWVRPdlZrbmEzTm0xZFl4ODJudWtzekVJdzBTTzg3REZYOVF2NWE5OWFyTlE5MFJBUXZORlducFZRVjJwWTFmZz09QGF6bWNjb3Ntb3NkYi5tb25nby5jb3Ntb3MuYXp1cmUuY29tOjEwMjU1Lz9zc2w9dHJ1ZSZyZXBsaWNhU2V0PWdsb2JhbGRiJnJldHJ5d3JpdGVzPWZhbHNlJm1heElkbGVUaW1lTVM9MTIwMDAwJmFwcE5hbWU9QGF6bWNjb3Ntb3NkYkA=
  WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9dWRjdGF6bWNzdGc7QWNjb3VudEtleT1PekRqeUFXWE1ReGJGR01VcXpZNkdreS9RRkZzZmZtRDRxbXVQaEtkTDd1c2t2OFNQQ3RQUTRuQTJwL05OK2s3K2tNVHY1THdJcTRPK0FTdFJmcHVBUT09
  WEBSITE_CONTENTSHARE: dWRjdGF6bWNhcGk0M2RmOWJkNTcwMGU=
apiVersion: v1
kind: Secret
metadata:
  name: udctazmcapi
---
data:
  host.master: cFBYWjhsNENwSlVESXVqaW1WdEY1dHFmTzBxYm9pcnJ4WWFYX3hVTDVZdWdBekZ1WUpBWFVnPT0=
  host.function.default: X2lqaUdHVGpuZHRNYU95TVloS2QzOUZfN245SWhpSGMzR0xpYV9IN3hpTl9BekZ1VG0zUDdBPT0=
  host.systemKey.default: azd3X1R0aWowcFR0M3hyNDVka3lfMEgxR3cyU2g3Zm5PcklXMm0wNy16dGFBekZ1TUJHRktBPT0=
  functions.deleteadvertisement.default: VHo3R1VWS09tc3FPcE9rSWxMajBBYWc5RVFfdEoxUFZOZGZLc2JJcC05d1dBekZ1QkRZYVBRPT0=
  functions.getpost.default: bU1VSWYtd2NIY2NLSjZ0bHhqRmNma0YxcWhiYkM2aE9ScWlDZEktQ0VUSmlBekZ1VUw4UDRnPT0=
  functions.getadvertisement.default: SDFMZF9ZRXlGaTd6dXZuaml5RzRXaDBnZElqWmpFS3hITVEzQ25vd2tjUFBBekZ1eFRINW13PT0=
  functions.createadvertisement.default: UHE5bjczV2xKQ3NyQlo1VzVwcVRZdEZva19fRlhIVE1jaHpZYnBFRzR6UldBekZ1bWRGLUtnPT0=
  functions.getadvertisements.default: SFpVd3FSVnQwSGh0dzF0SFJLNG5LZWF0OU5YeThEUHRrUWJRbjhFNkxldmpBekZ1LWxyXzlnPT0=
  functions.updateadvertisement.default: YnVsMEw4YmZJb2RTeWtWNC01Q3htUEZCVmN3bnJhSGFMNHRLdzVObXVlRFZBekZ1QnZZNE53PT0=
  functions.getposts.default: SE1GVm9McHpxeHlBRi1scGRpcnpCUW9FR0h3aXRNYm1NeG1XX01Ib1lhSGRBekZ1TXVFT2x3PT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-udctazmcapi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: udctazmcapi-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: udctazmcapi-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: udctazmcapi-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: udctazmcapi-http
spec:
  selector:
    app: udctazmcapi-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udctazmcapi-http
  labels:
    app: udctazmcapi-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udctazmcapi-http
  template:
    metadata:
      labels:
        app: udctazmcapi-http
    spec:
      containers:
      - name: udctazmcapi-http
        image: udctmcacr.azurecr.io/udctazmcapi:latest
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: getPost
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__4
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__5
          value: updateAdvertisement
        - name: AzureFunctionsJobHost__functions__6
          value: getPosts
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-udctazmcapi
        envFrom:
        - secretRef:
            name: udctazmcapi
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: udctazmcapi-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udctazmcapi
  labels:
    app: udctazmcapi
spec:
  selector:
    matchLabels:
      app: udctazmcapi
  template:
    metadata:
      labels:
        app: udctazmcapi
    spec:
      containers:
      - name: udctazmcapi
        image: udctmcacr.azurecr.io/udctazmcapi:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: udctazmcapi
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: udctazmcapi-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: udctazmcapi
  labels: {}
spec:
  scaleTargetRef:
    name: udctazmcapi
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

